"""Database migration runner for FichaFácil.

This lightweight runner keeps the project dependency-free while still
introducing versioned, idempotent schema migrations.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

MIGRATIONS_DIR = Path(__file__).resolve().parent / "migrations"
SCHEMA_MIGRATIONS_TABLE = "schema_migrations"


@dataclass(frozen=True)
class Migration:
    version: str
    path: Path
    sql: str


def _load_migrations() -> list[Migration]:
    migrations: list[Migration] = []
    for path in sorted(MIGRATIONS_DIR.glob("*.sql")):
        sql = path.read_text(encoding="utf-8").strip()
        if not sql:
            continue
        migrations.append(Migration(version=path.stem, path=path, sql=sql))
    return migrations


def _render_sql_for_dialect(sql: str, *, dialect_name: str) -> str:
    """Render portable migration SQL for the active database dialect.

    The committed migrations intentionally use SQLite-compatible SQL because
    local development/tests run on SQLite. For production PostgreSQL, translate
    the small set of dialect differences used by the initial schema.
    """
    if dialect_name != "postgresql":
        return sql

    replacements = {
        "INTEGER PRIMARY KEY AUTOINCREMENT": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "DATETIME": "TIMESTAMP",
        "BOOLEAN NOT NULL DEFAULT 1": "BOOLEAN NOT NULL DEFAULT TRUE",
    }
    rendered = sql
    for old, new in replacements.items():
        rendered = rendered.replace(old, new)
    return rendered


def _split_sql_statements(sql: str) -> list[str]:
    """Split SQL migration text into executable statements."""
    return [part.strip() for part in sql.split(";") if part.strip()]


async def _ensure_migrations_table(conn: AsyncConnection) -> None:
    await conn.execute(
        text(
            f"""
            CREATE TABLE IF NOT EXISTS {SCHEMA_MIGRATIONS_TABLE} (
                version VARCHAR(64) PRIMARY KEY,
                applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
    )


async def _applied_versions(conn: AsyncConnection) -> set[str]:
    result = await conn.execute(text(f"SELECT version FROM {SCHEMA_MIGRATIONS_TABLE}"))
    return {row[0] for row in result.fetchall()}


async def apply_migrations(conn: AsyncConnection) -> list[str]:
    """Apply any pending SQL migrations in order.

    Returns the list of versions applied during this run.
    """
    await _ensure_migrations_table(conn)
    applied = await _applied_versions(conn)
    pending = [migration for migration in _load_migrations() if migration.version not in applied]

    applied_now: list[str] = []
    dialect_name = conn.dialect.name
    for migration in pending:
        rendered_sql = _render_sql_for_dialect(migration.sql, dialect_name=dialect_name)
        for statement in _split_sql_statements(rendered_sql):
            await conn.execute(text(statement))
        await conn.execute(
            text(f"INSERT INTO {SCHEMA_MIGRATIONS_TABLE} (version) VALUES (:version)"),
            {"version": migration.version},
        )
        applied_now.append(migration.version)

    return applied_now
