import asyncio
import importlib
import os
import sqlite3
import sys
import tempfile
import unittest
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))


class DatabaseMigrationTests(unittest.TestCase):
    def setUp(self):
        for module_name in ["app.config", "app.database", "app.migrations"]:
            sys.modules.pop(module_name, None)

    def tearDown(self):
        for key in ["SECRET_KEY", "DATABASE_URL", "DEBUG"]:
            os.environ.pop(key, None)
        for module_name in ["app.config", "app.database", "app.migrations"]:
            sys.modules.pop(module_name, None)

    def test_init_db_applies_versioned_schema_migrations(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = Path(tmpdir) / "fichafacil.db"
            os.environ["SECRET_KEY"] = "0123456789abcdef0123456789abcdef"
            os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{db_path}"
            os.environ["DEBUG"] = "false"

            database = importlib.import_module("app.database")
            asyncio.run(database.init_db())
            asyncio.run(database.init_db())

            with sqlite3.connect(db_path) as conn:
                tables = {
                    row[0]
                    for row in conn.execute(
                        "SELECT name FROM sqlite_master WHERE type='table'"
                    ).fetchall()
                }
                applied_versions = [
                    row[0]
                    for row in conn.execute(
                        "SELECT version FROM schema_migrations ORDER BY version"
                    ).fetchall()
                ]

            self.assertTrue({"negocios", "users", "fichajes", "correcciones"}.issubset(tables))
            self.assertEqual(applied_versions, ["001_initial_schema"])

    def test_postgresql_renderer_translates_sqlite_only_schema_bits(self):
        migrations = importlib.import_module("app.migrations")
        sqlite_sql = (BACKEND_ROOT / "app" / "migrations" / "001_initial_schema.sql").read_text()

        rendered = migrations._render_sql_for_dialect(sqlite_sql, dialect_name="postgresql")

        self.assertNotIn("AUTOINCREMENT", rendered)
        self.assertNotIn("DATETIME", rendered)
        self.assertNotIn("DEFAULT 1", rendered)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", rendered)
        self.assertIn("BOOLEAN NOT NULL DEFAULT TRUE", rendered)
        self.assertIn("TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP", rendered)

    def test_render_postgres_url_is_normalized_to_asyncpg(self):
        os.environ["SECRET_KEY"] = "0123456789abcdef0123456789abcdef"
        os.environ["DATABASE_URL"] = "postgres://user:pass@example.com:5432/fichafacil"
        os.environ["DEBUG"] = "false"

        database = importlib.import_module("app.database")

        self.assertEqual(
            database.database_url,
            "postgresql+asyncpg://user:pass@example.com:5432/fichafacil",
        )


if __name__ == "__main__":
    unittest.main()
